### ISSUE TITLE
class not instance error 

### ISSUE THREAD

**Issue by mohsin111** [traex/CalendarListview#10]
The following classes could not be instantiated:
- com.example.caledarlistlib.DayPickerView (Open Class, Show Error Log)
See the Error Log (Window > Show View) for more details.
Tip: Use View.isInEditMode() in your custom views to skip code when shown in Eclipse

java.lang.UnsupportedOperationException: Unsupported Service: accessibility
    at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:465)
    at android.support.v7.widget.RecyclerView.<init>(RecyclerView.java:290)
    at com.example.caledarlistlib.DayPickerView.<init>(DayPickerView.java:28)
    at com.example.caledarlistlib.DayPickerView.<init>(DayPickerView.java:24)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(NativeConstructorAccessorImpl.java:-2)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at com.android.ide.eclipse.adt.internal.editors.layout.ProjectCallback.instantiateClass(ProjectCallback.java:438)
    at com.android.ide.eclipse.adt.internal.editors.layout.ProjectCallback.loadView(ProjectCallback.java:190)
    at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:207)
    at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:132)
    at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:806)
    at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:782)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:385)

**Comment by guanchao** [comment]
anyone who can solve this bug?

**Comment by guanchao** [comment]
anyone who can solve this bug?
